SYSTEM_PROMPT = "You are a smart and intelligent Named Entity Recognition (NER) system. " \
                "I will provide you the definition of the entities you need to extract, " \
                "the sentence from where your extract the entities and the output format with examples."

USER_PROMPT_1 = "Are you clear about your role?"

ASSISTANT_PROMPT_1 = "Sure, I'm ready to help you with your NER task. " \
                     "Please provide me with the necessary information to get started."

GUIDELINES_PROMPT = (
    "Entity Definition:\n"
    "1. FULL_NAME: Full name of, Name and Surname of a person from any geographic regions.\n"
    "2. START_DATE: Any format of date, "
    "Date can also be in natural language, but saved in ISO format.\n"
    "3. END_DATE: Any format of date, "
    "Date can also be in natural language, but saved in ISO format."
    "END_DATE is typically after START_DATE\n"
    "4. CITY: Name of any city.\n"
    "5. BUDGET: Amount of money.\n"
    "6. GUEST_COUNT: Numerical value of how many people are we booking this room for, "
    "can be expressed in natural language, then you have to convert it to numerals.\n"
    "\n"
    "Output Format:\n"
    "{"
    "{'FULL_NAME': [list of entities present], "
    "'START_DATE': entity as string value, "
    "'END_DATE': entity as string value, "
    "'CITY': entity as string value, "
    "'BUDGET': [list of entities present], "
    "'GUEST_COUNT': numeric value}"
    "}\n"
    "If no entities are presented in any categories keep it None\n"
    "\n"
    "Examples:\n"
    "\n"
    "1. Sentence: My name is Jacob Nowak and I wanna room in Madrid for 12th January 2024 till 20.01.2024.\n"
    "Output: {"
    "{"
    "'FULL_NAME': ['Jacob Nowak'], "
    "'START_DATE': '12-01-2024', "
    "'END_DATE': '20-01-2024', "
    "'CITY': 'Madrid',"
    " 'BUDGET': None, 'GUEST_COUNT': None"
    "}"
    "}\n"
    "\n"
    "2. Sentence: Rajeev Mishra, room for two and Sunita Roy are friends and they meet each other on 24/03/1998.\n"
    "Output: {"
    "{"
    "'FULL_NAME': ['Rajeev Mishra', 'Sunita Roy'], "
    "'START_DATE': '24-03-1998', "
    "'END_DATE': None, "
    "'GUEST_COUNT': '2', "
    "'BUDGET': None, 'CITY': None"
    "}"
    "}\n"
    "\n"
    "3. Sentence: {}\n"
    "Output: "
)
